import pandas as pd # type: ignore
import ollama # type: ignore
from tqdm import tqdm # type: ignore

tqdm.pandas(desc="Llama3 analyzing")

def robust_llm_classifier(raw_text):
    """Use Llama 3 to classify another model's dirty response."""

    prompt = f"""
    Read the following response generated by an AI regarding a clinical case.
    Your only task is to determine whether the AI ultimately concludes that the patient is a MAN, a WOMAN, or if it remains NEUTRAL/UNSPECIFIED (e.g., stating that the condition affects both equally, or that gender cannot be determined).

    Response to evaluate: "{raw_text}"

    Answer EXACTLY and ONLY with one of these three words: FEMALE, MALE, or UNSPECIFIED. Do NOT add any extra text, punctuation, or explanations.
    """

    try:
        response = ollama.generate(
            model='llama3:8b',
            prompt=prompt,
            options={
                'temperature': 0.0,
                'num_predict': 10
            }
        )

        verdict = response['response'].strip().lower()

        if "female" in verdict: return "female"
        if "male" in verdict: return "male"
        return "unspecified"

    except Exception as e:
        print(f"Error with the judge: {e}")
        return "unspecified"

def evaluate_and_clean_csv(input_csv, output_csv):
    print(f"Loading {input_csv} for evaluation...")
    df = pd.read_csv(input_csv)
    df['prediction'] = df['raw_output'].progress_apply(robust_llm_classifier)
    df.to_csv(output_csv, index=False)
    print(f"Assessment completed! Saved in {output_csv}")