Llama_3 = "llama3:8b"
Mistral = "mistral:7b"
DeepSeek = "deepseek-llm:7b"
Gemma_3 = "gemma3:4b"
Qwen_2_5 = "qwen2.5:7b"
Salamandra = "cas/salamandra-7b-instruct"
MentaLLaMA = "vitorcalvi/mentallama2"
#Llama_3_de_biased = "andreslilloortiz/llama3-3b-de-biased"