BERT_base = "google-bert/bert-base-uncased"
DisorBERT = "citiusLTL/DisorBERT"
DepBERT = "citiusLTL/DepBERT"
SHBERT = "citiusLTL/SHBERT"
GambBERT = "citiusLTL/GambBERT"
AnorBERT = "citiusLTL/AnorBERT"
WholeBERT = "citiusLTL/WholeBERT"
SHBERT_de_biased = "andreslilloortiz/SHBERT-de-biased"